#!/usr/bin/env python3
import argparse
import requests
import json
import pandas as pd

parser = argparse.ArgumentParser()
parser.add_argument('--format', choices=['json','csv'], help='', required='TRUE')
parser.add_argument('--op1', help='Το ID του operator', required='TRUE')
parser.add_argument('--datefrom', help='Η αιτούμενη περίοδος (από)', required='TRUE')
parser.add_argument('--dateto', help='Η αιτούμενη περίοδος (έως)', required='TRUE')
args = parser.parse_args()

baseurl = 'https://localhost:9103/interoperability/api'
url = baseurl + '/ChargesBy/' + args.op1 + '/' + str(args.datefrom) + '/' + str(args.dateto)
#print(url)

res = requests.get(url)
obj = res.json()

if(args.format == 'csv'):
    df = pd.DataFrame(res.json()['PPOList'])
    df.to_csv('ChargesBy.csv', index=None, sep=';')
else:
    print(json.dumps(obj, indent=4))